name: Build
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:

  lint-test-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Unit tests
        run: npm run test

      - name: Attempt production build
        run: npm run build

  gh-pages:
    if: github.repository == 'geonetwork/geonetwork-ui'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: npm ci
      - name: Build webcomponents
        run: npm run build:wc
      - name: Build storybook
        run: npm run build:storybook
      - name: Build webcomponents in production mode and demo pages
        run: npm run build:demo

      - run: echo "::set-env name=BRANCH_NAME::${GITHUB_HEAD_REF:-master}"

      - name: deploy to gh pages
        run: |
          echo "Deploying to directory: ${{env.BRANCH_NAME}}"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          npx gh-pages --dist dist/ --dest ${{env.BRANCH_NAME}} --remove "${{env.BRANCH_NAME}}/**" --no-history --repo "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
      - name: add PR comment
        uses: unsplash/comment-on-pr@master
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'Link to gh-pages:

                * https://geonetwork.github.io/geonetwork-ui/${{env.BRANCH_NAME}}/demo/

                * https://geonetwork.github.io/geonetwork-ui/${{env.BRANCH_NAME}}/storybook/

                * https://geonetwork.github.io/geonetwork-ui/${{env.BRANCH_NAME}}/storybook-wc/'
          check_for_duplicate_msg: true
